### ISSUE TITLE
About adjacency matrix

### ISSUE THREAD

**Issue by HongxuanZhang** [chaitjo/learning-tsp#7]
Hi there. 

According to your code,  the adjacency matrix of a graph uses 0 to indicate that two nodes are connected,  and 1 to indicate that two nodes are not connected. This seems to be different from routine which uses 1 to represent connected.  I'm curious why you chose such an implementation?

If I use 1 to represent two nodes are connected,  does that would affect me to extend your code to other graph combinatorial optimization problems?

Thanks for any reply!

**Comment by chaitjo** [comment]
https://github.com/chaitjo/learning-tsp/blob/master/nets/encoders/gat_encoder.py#L55

https://github.com/chaitjo/learning-tsp/blob/master/nets/encoders/gnn_encoder.py#L117

Sorry for the late, brief response. The idea was to make it easy to enforce sparsity by indexing the mask where it had value 1/True to indicate that the edge doesn't exist. Today, I would just use PyG or DGL!
